/*
Copyright 2019 Gravitational, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/gravitational/wormhole/pkg/apis/wormhole.gravitational.io/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeWGNodes implements WGNodeInterface
type FakeWGNodes struct {
	Fake *FakeWormholeV1beta1
}

var wgnodesResource = schema.GroupVersionResource{Group: "wormhole.gravitational.io", Version: "v1beta1", Resource: "wgnodes"}

var wgnodesKind = schema.GroupVersionKind{Group: "wormhole.gravitational.io", Version: "v1beta1", Kind: "WGNode"}

// Get takes name of the wGNode, and returns the corresponding wGNode object, and an error if there is any.
func (c *FakeWGNodes) Get(name string, options v1.GetOptions) (result *v1beta1.WGNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(wgnodesResource, name), &v1beta1.WGNode{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.WGNode), err
}

// List takes label and field selectors, and returns the list of WGNodes that match those selectors.
func (c *FakeWGNodes) List(opts v1.ListOptions) (result *v1beta1.WGNodeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(wgnodesResource, wgnodesKind, opts), &v1beta1.WGNodeList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.WGNodeList{ListMeta: obj.(*v1beta1.WGNodeList).ListMeta}
	for _, item := range obj.(*v1beta1.WGNodeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested wGNodes.
func (c *FakeWGNodes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(wgnodesResource, opts))
}

// Create takes the representation of a wGNode and creates it.  Returns the server's representation of the wGNode, and an error, if there is any.
func (c *FakeWGNodes) Create(wGNode *v1beta1.WGNode) (result *v1beta1.WGNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(wgnodesResource, wGNode), &v1beta1.WGNode{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.WGNode), err
}

// Update takes the representation of a wGNode and updates it. Returns the server's representation of the wGNode, and an error, if there is any.
func (c *FakeWGNodes) Update(wGNode *v1beta1.WGNode) (result *v1beta1.WGNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(wgnodesResource, wGNode), &v1beta1.WGNode{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.WGNode), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeWGNodes) UpdateStatus(wGNode *v1beta1.WGNode) (*v1beta1.WGNode, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(wgnodesResource, "status", wGNode), &v1beta1.WGNode{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.WGNode), err
}

// Delete takes name of the wGNode and deletes it. Returns an error if one occurs.
func (c *FakeWGNodes) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(wgnodesResource, name), &v1beta1.WGNode{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeWGNodes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(wgnodesResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.WGNodeList{})
	return err
}

// Patch applies the patch and returns the patched wGNode.
func (c *FakeWGNodes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.WGNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(wgnodesResource, name, pt, data, subresources...), &v1beta1.WGNode{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.WGNode), err
}
