/*
Copyright 2019 Gravitational, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	v1beta1 "github.com/gravitational/wormhole/pkg/apis/wormhole.gravitational.io/v1beta1"
	scheme "github.com/gravitational/wormhole/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// WGNodesGetter has a method to return a WGNodeInterface.
// A group's client should implement this interface.
type WGNodesGetter interface {
	WGNodes() WGNodeInterface
}

// WGNodeInterface has methods to work with WGNode resources.
type WGNodeInterface interface {
	Create(*v1beta1.WGNode) (*v1beta1.WGNode, error)
	Update(*v1beta1.WGNode) (*v1beta1.WGNode, error)
	UpdateStatus(*v1beta1.WGNode) (*v1beta1.WGNode, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.WGNode, error)
	List(opts v1.ListOptions) (*v1beta1.WGNodeList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.WGNode, err error)
	WGNodeExpansion
}

// wGNodes implements WGNodeInterface
type wGNodes struct {
	client rest.Interface
}

// newWGNodes returns a WGNodes
func newWGNodes(c *WormholeV1beta1Client) *wGNodes {
	return &wGNodes{
		client: c.RESTClient(),
	}
}

// Get takes name of the wGNode, and returns the corresponding wGNode object, and an error if there is any.
func (c *wGNodes) Get(name string, options v1.GetOptions) (result *v1beta1.WGNode, err error) {
	result = &v1beta1.WGNode{}
	err = c.client.Get().
		Resource("wgnodes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of WGNodes that match those selectors.
func (c *wGNodes) List(opts v1.ListOptions) (result *v1beta1.WGNodeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.WGNodeList{}
	err = c.client.Get().
		Resource("wgnodes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested wGNodes.
func (c *wGNodes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("wgnodes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a wGNode and creates it.  Returns the server's representation of the wGNode, and an error, if there is any.
func (c *wGNodes) Create(wGNode *v1beta1.WGNode) (result *v1beta1.WGNode, err error) {
	result = &v1beta1.WGNode{}
	err = c.client.Post().
		Resource("wgnodes").
		Body(wGNode).
		Do().
		Into(result)
	return
}

// Update takes the representation of a wGNode and updates it. Returns the server's representation of the wGNode, and an error, if there is any.
func (c *wGNodes) Update(wGNode *v1beta1.WGNode) (result *v1beta1.WGNode, err error) {
	result = &v1beta1.WGNode{}
	err = c.client.Put().
		Resource("wgnodes").
		Name(wGNode.Name).
		Body(wGNode).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *wGNodes) UpdateStatus(wGNode *v1beta1.WGNode) (result *v1beta1.WGNode, err error) {
	result = &v1beta1.WGNode{}
	err = c.client.Put().
		Resource("wgnodes").
		Name(wGNode.Name).
		SubResource("status").
		Body(wGNode).
		Do().
		Into(result)
	return
}

// Delete takes name of the wGNode and deletes it. Returns an error if one occurs.
func (c *wGNodes) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("wgnodes").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *wGNodes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("wgnodes").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched wGNode.
func (c *wGNodes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.WGNode, err error) {
	result = &v1beta1.WGNode{}
	err = c.client.Patch(pt).
		Resource("wgnodes").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
